services:
  - type: web
    name: gerenciador-times
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1